{
    "name": "Product Family Triplet",
    "summary": "Famille / Sous-famille / Sous-sous-famille avec création automatique des catégories et analytique",
    "version": "3.0",
    "author": "ALEBOR",
    "license": "LGPL-3",
    "depends": [
        "product",
        "stock",
        "stock_account",
        "analytic",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/product_family_views.xml",
        "views/product_subfamily_views.xml",
        "views/product_subsubfamily_views.xml",
        "views/product_family_triplet_views.xml",
        "views/product_family_menu.xml",
        "views/product_template_views.xml",
    ],
    "installable": True,
    "application": False,
}
